#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

HERE="$(cd "$(dirname "$0")" && pwd)"
TOP_LEVEL="$(cd "$HERE/../" && pwd)"

cd "$TOP_LEVEL"

# Build
if [ -x "$(which xcpretty)" ]; then
    xcodebuild | xcpretty
else
    xcodebuild
fi

# Deploy
rm -rf deploy
mkdir -p deploy
( cd build/Release && zip -r "${TOP_LEVEL}/deploy/Chai.zip" Chai.app )

