#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

HERE="$(cd "$(dirname "$0")" && pwd)"
TOP_LEVEL="$(cd "$HERE/../" && pwd)"

cd "$TOP_LEVEL"

git ls-files -z '*.swift' | xargs -0 swift-format format -i
